"""Generate the native Swift skin catalog from Wyrm's authoritative C data.

The generated file is committed so the SwiftUI editor never asks the live
engine to expose its renderer or tables. Re-running this script after an engine
asset update makes table drift reviewable in a normal source diff.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
GAME_DATA = (ROOT / "SharedEngine/app/src/game/game_data.c").read_text()
TAG_TABLE = (ROOT / "SharedEngine/app/src/game/tag_table.h").read_text()
BACKGROUNDS = (ROOT / "SharedEngine/app/src/game/backgrounds.h").read_text()


def balanced_block(text: str, marker: str) -> str:
    start = text.index(marker)
    start = text.index("{", start)
    depth = 0
    for end in range(start, len(text)):
        if text[end] == "{":
            depth += 1
        elif text[end] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:end]
    raise RuntimeError(f"unterminated block after {marker}")


skin_block = balanced_block(GAME_DATA, ".default_skins =")
skin_rows = re.findall(r"\[(\d+)\]\s*=\s*\{([^}]*)\}", skin_block, re.S)
presets = []
for raw_index, raw_values in skin_rows:
    values = [int(value) for value in re.findall(r"\d+", raw_values)]
    length, groups = values[0], values[1:]
    assert length == len(groups), (raw_index, length, groups)
    presets.append((int(raw_index), groups))
assert [index for index, _ in presets] == list(range(66))

tag_pattern = re.compile(
    r"\{(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+),\s*"
    r"(0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+),\s*(\d+),\s*"
    r"\{([0-9.]+)f,\s*([0-9.]+)f,\s*([0-9.]+)f,\s*([0-9.]+)f\}\}"
)
tags = [match.groups() for match in tag_pattern.finditer(TAG_TABLE)]
assert len(tags) == 164, len(tags)

background_pattern = re.compile(
    r'\{"([^"]+)",\s*"([^"]+)",\s*(NULL|"[^"]+")\s*,\s*'
    r'([0-9.]+)f,\s*([0-9.]+)f\}'
)
backgrounds = [match.groups() for match in background_pattern.finditer(BACKGROUNDS)]
assert len(backgrounds) == 22, len(backgrounds)

scales = [None] * 32
offsets = [None] * 32
for index, raw in re.findall(r"accessories\[(\d+)\]\.sc\s*=\s*(-?[0-9.]+)f?;", GAME_DATA):
    scales[int(index)] = float(raw)
for index, raw in re.findall(r"accessories\[(\d+)\]\.of\s*=\s*(-?[0-9.]+)f?;", GAME_DATA):
    offsets[int(index)] = float(raw)
assert all(value is not None for value in scales + offsets)

group_codes = ["z", "x", "c", "v", "b", "n", "m", ",", "a", "s", "d", "f", "g", "h", "j", "k", "l", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "1", "2", "3", "4", "5", "6", "7", "8", "9", "*", "0", "*", "-", "*", "*"]

lines = [
    "// Generated by Scripts/generate-swift-skin-catalog.py. Do not edit.",
    "import Foundation",
    "",
    "struct WyrmTagAsset: Identifiable, Hashable {",
    "    let id: Int", "    let width: Int", "    let height: Int",
    "    let anchorX: Int", "    let anchorY: Int", "    let accentA: UInt32",
    "    let accentB: UInt32", "    let ntlID: Int", "    let minU: Double",
    "    let minV: Double", "    let maxU: Double", "    let maxV: Double", "}", "",
    "struct WyrmArenaBackgroundAsset: Identifiable, Hashable {",
    "    let id: Int", "    let key: String", "    let label: String",
    "    let resourcePath: String?", "    let tileWidth: Double", "    let tileHeight: Double", "}", "",
    "struct WyrmAccessoryAsset: Identifiable, Hashable {",
    "    let id: Int", "    let scale: Double", "    let offset: Double", "}", "",
    "enum WyrmSkinCatalog {",
    "    static let validGroups = Array(0...41).filter { ![36, 38, 40, 41].contains($0) }",
    "    static let groupCodes: [Character] = [" + ", ".join(f'\"{value}\"' for value in group_codes) + "]",
    "    static let presets: [[Int]] = [",
]
for _, groups in presets:
    lines.append("        [" + ", ".join(map(str, groups)) + "],")
lines.extend(["    ]", "", "    static let accessories: [WyrmAccessoryAsset] = ["])
for index, (scale, offset) in enumerate(zip(scales, offsets)):
    lines.append(f"        .init(id: {index}, scale: {scale:g}, offset: {offset:g}),")
lines.extend(["    ]", "", "    static let tags: [WyrmTagAsset] = ["])
for index, tag in enumerate(tags):
    w, h, bx, by, c1, c2, ntl, u, v, uw, vh = tag
    lines.append(
        f"        .init(id: {index}, width: {w}, height: {h}, anchorX: {bx}, anchorY: {by}, "
        f"accentA: {c1}, accentB: {c2}, ntlID: {ntl}, minU: {u}, minV: {v}, maxU: {uw}, maxV: {vh}),"
    )
lines.extend(["    ]", "", "    static let backgrounds: [WyrmArenaBackgroundAsset] = ["])
for index, (key, label, path, tile_w, tile_h) in enumerate(backgrounds):
    resource = "nil" if path == "NULL" else f'"{path.strip(chr(34)).replace("app/res/", "res/")}"'
    lines.append(
        f'        .init(id: {index}, key: "{key}", label: "{label}", resourcePath: {resource}, '
        f"tileWidth: {tile_w}, tileHeight: {tile_h}),"
    )
lines.extend([
    "    ]", "",
    "    static func code(for groups: [Int]) -> String {",
    "        String(groups.prefix(64).compactMap { groupCodes.indices.contains($0) && validGroups.contains($0) ? groupCodes[$0] : nil })",
    "    }", "}", "",
])

output = ROOT / "SourcesShell/WyrmSkinCatalog.generated.swift"
output.write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {output.name}: {len(presets)} presets, {len(tags)} tags, {len(backgrounds)} backgrounds")
